### ISSUE TITLE
[TRAIN] - Larger Size Model Request

### ISSUE THREAD

**Issue by ao-zz** [ankandrew/yolox-models#1]
### Model
YOLOX **s** or **m**

### Classes
Human face

### Object Area
I'd like objects that have an area greater or equal than 1%.

Thanks a lot !

**Comment by ankandrew** [comment]
Hi! After Google Colab introduced credits system I stopped paying, so I don't have anywhere (without paying) to train the model. I've been using lately `lambdaclouds` (paying on-demand). I committed to the repo the notebook I used to train the models, so you can train it. I've also added the notebook to generate the dataset from OpenImagesV6.

**Comment by ao-zz** [comment]
That would be of great help, thank you : )
